### ISSUE TITLE
How do I get nested documents working?

### ISSUE THREAD

**Issue by peek4y** [SierraSoftworks/Iridium#26]
User Schema/Model.
```javascript
function User() {
  Iridium.Instance.apply(this, arguments);
  
  this.addAddress = (address) => this.address.push(address);
}
require('util').inherits(User, Iridium.Instance);

User.schema = {
  _id: false,
  username: String,
  address: [Address.schema]
};
User.collection = 'users';
```

Address Schema/Model
``` javascript
Address.schema = {
  _id: false,
  ZipCode: { $type: String, $required: true }
};
Address.onCreating = (document) => console.log('Adding a new address');
Address.collection = 'address';
```

I have an Object like..

```javascript
{
   username: "test",
   address: [{}]
}
```
it does not validate the address schema, and also how do I get the address document validated & inserted with an ObjectID as part of User? (like in Mongoose)

**Comment by SPARTAN563** [comment]
Just checking if I'm following correctly here - it looks like you're trying to do a transparent join between the **address** and **user** collections? I assume you then wish to have **user.address** (in the database) be an array of ObjectID fields which are translated back into an array of addresses when you fetch the User?

If that is the case, then it isn't something supported by Iridium out of the box, as joins are a bit of an anti-pattern in the MongoDB world. The recommended approach is simply to store the address information in its entirety within the User document.

```typescript
interface UserDocument {
  _id?: string; // ObjectIDs are represented as strings
  username: string;
  address: Address[];
}

interface Address {
  ZipCode: string;
}

const AddressSchema = {
  ZipCode: String
};

class User extends Iridium.Instance<UserDocument, User> {
  _id: string;
  username: string;
  address: AddressSchama[];

  static schema = {
    _id: false,
    username: String,
    address: [AddressSchema]
  };

  addAddress(address: Address) {
    this.address.push(address);
  }

  static onCreating(doc: UserDocument) {
    console.log('Creating user');
  }
}
```

**Comment by peek4y** [comment]
Hmm, 

So, when I create a User with an Object like 
``` javascript
{
   username: "test",
   address: [{
      zipcode: "TestCode"
   }]
}
```

It should save in DB, and the document is something like..

```javascript
 {
    _id: ObjectId('asdasd'),
    username: 'test',
    address: [{
          _id: ObjectId('asdasd'),
          zipcode: 'TestCode'
    }]
 }
```

This isn't supported by Iridium right?

**Comment by SPARTAN563** [comment]
That's more or less correct - Iridium will allow MongoDB to populate the `_id` field on the top level object (if you haven't provided it already) but if you need to add `_id` to your address objects, you will need to make use of a [`transform`](http://sierrasoftworks.github.io/Iridium/interfaces/transforms.html).

**Comment by SPARTAN563** [comment]
Out of curiosity, is there a reason you are looking to have `_id` fields on each of the address objects?

**Comment by peek4y** [comment]
Nothing specific, I noticed the nested schema generates ObjectID for each document in Mongoose, so was wondering if that's possible in Iridium as well.

Also, we are just mentioning the AddressSchema to the address property and not the InstanceType right? Then how will it trigger transforms ? Or even behave like an Instance?

**Comment by SPARTAN563** [comment]
I see, okay.

That's right, the schema is only for validation - however you can apply a transform on a per-property basis (in this case the `address` property) and do whatever processing you wish to on there.

**Comment by peek4y** [comment]
Can't find documentation on transform per-property, can you please link me to it?

**Comment by SPARTAN563** [comment]
Sure, property [`transforms`](http://sierrasoftworks.github.io/Iridium/interfaces/transforms.html) are defined using the [`transforms`](http://sierrasoftworks.github.io/Iridium/interfaces/instanceimplementation.html#transforms) static property on your instance class.

Specifically, instead of using [`$document`](http://sierrasoftworks.github.io/Iridium/interfaces/transforms.html#_document) you would simply use the name of the property you wish to apply the transform to.

```typescript
class User extends Iridium.Instance<UserDocument, User> {
  static transforms = {
    address: {
      fromDB: value => value,
      toDB: value => {
        value.forEach(address => {
            if(!address._id) address._id = newAddressID();
        });
        return value;
      }
    }
  };
}
```

**Comment by peek4y** [comment]
Ah, yes got it. Thanks for clarifying!
