### ISSUE TITLE
Unique Indexes.

### ISSUE THREAD

**Issue by peek4y** [SierraSoftworks/Iridium#27]
Way to specify unique indexes in IndexSpecification?

**Comment by SPARTAN563** [comment]
You'll find that you can use either an [`Index`](http://sierrasoftworks.github.io/Iridium/interfaces/index.html#options) or [`IndexSpecification`](http://sierrasoftworks.github.io/Iridium/interfaces/indexspecification.html) for your indexes.

To specify any options for your index (`unique`, `sparse`, `background` etc), simply use the [`Index`](http://sierrasoftworks.github.io/Iridium/interfaces/index.html#options) style like this:

```typescript
class User extends Iridium.Instance<UserDocument, User> {
  static indexes = [
    { spec: { username: 1 }, options: { unique: true } }
  ];
}
```

Or, if you're using decorators, supply the second argument:

```typescript
@Iridium.Index({ username: 1 }, { unique: true })
class User extends Iridium.Instance<UserDocument, User> {
  
}
```

**Comment by peek4y** [comment]
Cool! Thanks, also what are your thoughts on ensureIndex function? It's marked deprecated in v3.0
https://docs.mongodb.org/v3.0/reference/method/db.collection.ensureIndex/.

Any plans on changing the API of ensureIndex -> createIndex?

**Comment by SPARTAN563** [comment]
Well spotted, they also mention that `ensureIndex` is now an alias for `createIndex` and that `createIndex` only operates if the index does not exist already - so there should be no issues with using it for the time being. Should they remove the `ensureIndex` function, I will ensure that Iridium transparently calls through to `createIndex` instead.

**Comment by peek4y** [comment]
Agreed.
