### ISSUE TITLE
Question on Update Result

### ISSUE THREAD

**Issue by peek4y** [SierraSoftworks/Iridium#28]
I see that only the nModified or result.n is being returned on update, [here](https://github.com/SierraSoftworks/Iridium/blob/master/lib/Model.ts#L554)

Is there a way I can get the WriteResult object itself on update? Would like to use the nUpserted property

**Comment by peek4y** [comment]
I'm getting an empty object ```{}``` on updating a document via ```Model.update()```  (Success case)

Need some clarification on what's the expected result should be.

**Comment by SPARTAN563** [comment]
Ah, that is a bit of an issue with the current implementation - in most cases the `nModified` is exactly the number people are looking for (as well as being backwards compatible), however if you absolutely need access to the original, then you can just call through to the underlying driver using `Model.collection.update(..., (err, result) => {})`.

The result in all cases when calling `update` should be the number of documents modified - not sure why you'd be getting an empty object unless the MongoDB driver was returning that for `result.nModified`...

**Comment by peek4y** [comment]
Not sure, I tried doing a simple update, I just got the empty  object, will have to debug it.

I'll try using the collection directly then.

**Comment by peek4y** [comment]
My bad, it was my stupid code change, that was showing the empty object :disappointed:  

Thanks for the help!

**Comment by SPARTAN563** [comment]
:+1:
