### ISSUE TITLE
How do I define $push $set ... update actions in Instance.save()'s changes argument?

### ISSUE THREAD

**Issue by peek4y** [SierraSoftworks/Iridium#29]
Is there a way to push a sub-document or set or edit?

**Comment by SPARTAN563** [comment]
Indeed, if you don't wish to let the built in diff algorithm figure out the changes for you, then you can simply supply an argument to the save method with the change operation you wish to apply to the document. 

Take a look at [Instance's Save method](http://sierrasoftworks.github.io/Iridium/classes/instance.html) - specifically the second case.

**Comment by peek4y** [comment]
Ah got it, thanks!
