### ISSUE TITLE
Lazy Loading.

### ISSUE THREAD

**Issue by peek4y** [SierraSoftworks/Iridium#31]
Is there a way, to define create models without an active DB connection? 

Something like how mongoose does?

**Comment by SPARTAN563** [comment]
You'll always require an `Iridium.Core` instance to register your models (which represents a database connection) however you never actually need to call `connect()` on it if you don't want to.

Similarly, if you wish to create an instance without going through the `.insert(...)`/`.create(...)` route (which hits the database) then you can use [`Model.Instance`](http://sierrasoftworks.github.io/Iridium/classes/model.html#instance) like this:

```typescript
let instance = new core.model.Instance({
  name: "testing"
});
```

Does that help?

**Comment by peek4y** [comment]
Hmmm, 

Here is what I mean.

I've a Instance - Xyz

So whenever I do a ```new Iridium.Model(Core, Xyz)``` (The core has not established to DB yet) It throws an error saying ```Message: You failed to provide a valid Iridium core for this model```

Hence, wondering if the connection can be deferred, or lazy loading, so that it doesn't become a blocker to create a Model.

**Comment by SPARTAN563** [comment]
The only time you should receive a `You failed to provide a valid Iridium core for this model` error is when you don't provide a core which inherits from `Iridium.Core` - the core only needs to be connected for operations which hit the database, so provided you've instantiated your Core you should be able to register Models against it - connecting to the database doesn't block it.

You can see examples of the exact workflow you're describing throughout most of the unit tests for Iridium.

**Comment by peek4y** [comment]
Yes, but when I try to register models, I get this error :( Not sure what's up

**Comment by peek4y** [comment]
Ugh, my bad. It works fine.

Thanks for the help.

**Comment by SPARTAN563** [comment]
No worries :smiley:
