### ISSUE TITLE
TypeScript compile error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#35]
TypeScript 1.8.10

![image](https://cloud.githubusercontent.com/assets/19378179/15296599/b475ea12-1b9e-11e6-85ee-0e118fc6c8c3.png)

![image](https://cloud.githubusercontent.com/assets/19378179/15296824/d0a3ee72-1b9f-11e6-9ee6-87ee020140e1.png)

head in index.ts
```typescript
/// <reference path="../typings/node/node.d.ts" />
/// <reference path="../typings/lib.es6/lib.es6.d.ts" />
/// <reference path="../typings/socket.io/socket.io.d.ts" />
/// <reference path="../typings/mongodb/mongodb.d.ts" />
/// <reference path="../typings/lodash/lodash.d.ts" />
/// <reference path="../typings/bluebird/bluebird.d.ts" />


```

tsconfig.json
```json
{
  "compilerOptions": {
    "experimentalAsyncFunctions": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "module": "commonjs",
    "sourceMap": true,
    "target": "ES6",
    "pretty": true
  },

  "externalTranspiler": "babel",

  "files": [
    "./server/index.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by SPARTAN563** [comment]
Hi Ivan,

Looks like it may be a lodash type definition issue - I've made an update in 7.0.0-alpha.6 to see if it fixes this (and also to improve the behaviour). Please take a look and let me know if it works for you or not.

Regards,
Benjamin

**Comment by uMaxmaxmaximus** [comment]
I'm new, tell me how to download the alpha npm module?  7.0.0-alpha.6

```npm install iridium 7.0.0-alpha.6 ?``
please tell command to set the alpha version

**Comment by SPARTAN563** [comment]
Hi Ivan,

Almost there, the version separator is the '@' symbol, so this should work.

`npm install iridium@7.0.0-alpha.7`

**Comment by uMaxmaxmaximus** [comment]
compile error

![image](https://cloud.githubusercontent.com/assets/19378179/15297295/f9d8ef5c-1ba1-11e6-98bb-bc496ac3aa8c.png)

![image](https://cloud.githubusercontent.com/assets/19378179/15297301/04c151de-1ba2-11e6-96fa-1edb85066015.png)

lodash.d.ts  4.0.0 Changelog (https://github.com/lodash/lodash/wiki/Changelog)

![image](https://cloud.githubusercontent.com/assets/19378179/15297333/34c3a6a2-1ba2-11e6-8c1f-4656ea175e1e.png)

**Comment by SPARTAN563** [comment]
That's really disappointing - let me take a look at the lodash typings file quickly, `forOwn` should be present according to the [docs](https://lodash.com/docs#forEach)

**Comment by uMaxmaxmaximus** [comment]
I change ext to load it =)


[lodash.d.txt](https://github.com/SierraSoftworks/Iridium/files/266591/lodash.d.txt)

**Comment by uMaxmaxmaximus** [comment]
you need white type iteration object

        forOwn<T extends {}>(
            object: T,
            iteratee?: ObjectIterator<any, any>
        ): T;

**Comment by uMaxmaxmaximus** [comment]
```typescript
        forOwn<T>(
            object: Dictionary<T>,
            iteratee?: DictionaryIterator<T, any>
        ): Dictionary<T>;
```

you specify the context of the challenges of the third argument, and does not support the definition of typescript type this inside the function, in this this option at all missed. This error lodash.d

**Comment by uMaxmaxmaximus** [comment]
this is fix error

```typescript
        forOwn<T>(
            object: Dictionary<T>,
            iteratee?: DictionaryIterator<T, any>,
            context?:any
        ): Dictionary<T>;

        /**
         * @see _.forOwn
         */
        forOwn<T extends {}>(
            object: T,
            iteratee?: ObjectIterator<any, any>,
            context?:any
        ): T;
```

**Comment by SPARTAN563** [comment]
Hi Ivan,

I've put out 7.0.0-alpha.7 (`npm install iridium@7.0.0-alpha.7`) which includes the latest lodash file, it appears to include the lines you've got there but please let me know if it doesn't solve the problem.

Regards,
Benjamin

**Comment by uMaxmaxmaximus** [comment]
occur the same mistakes. I said what's the problem. It is that in lodash.d not described the third parameter of the function indicating the context, even in the most recent version lodash.d.

If I remove the line in my script
/// <Reference path = "../ typings / lodash / lodash.d.ts" />
the write error "lodash mkdule in not found"

**Comment by SPARTAN563** [comment]
So this is what's in the latest lodash.d.ts file:

![image](https://cloud.githubusercontent.com/assets/1760260/15298945/5bd8e874-1ba2-11e6-9389-64ffdb134b6f.png)

Unfortunately I'm not getting any compiler errors on my side, any chance you have your own local type definition file which is out of date?

**Comment by uMaxmaxmaximus** [comment]
i use this https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/lodash.d.ts
this "official" lodash.d.ts , no?

![image](https://cloud.githubusercontent.com/assets/19378179/15299065/557f59c8-1bab-11e6-94ad-7db4f7ac4ded.png)

**Comment by SPARTAN563** [comment]
I see, I'm using this one, which I believe is a little more up to date: https://github.com/typed-typings/npm-lodash/blob/master/index.d.ts

**Comment by SPARTAN563** [comment]
DefinitelyTyped has been deprecated in favour of https://github.com/typings/typings

**Comment by uMaxmaxmaximus** [comment]
i dont know =) sorry. and you can not override the function for Own manually in your script, not to depend on the version lodash.d?

**Comment by uMaxmaxmaximus** [comment]
omn "typings"  is epic =)! 

Thank you, I have lived in darkness, let's close the ticket. but I also think that you should be somewhere in the documentation write depending on the framework files d.ts

**Comment by SPARTAN563** [comment]
I probably could, and it may well be something I look at doing going forward, but for now the lodash implementation is nice and reliable.

I actually should have checked that first, version 7 is the typings upgrade, while version 6 is using definitely typed. I'll make sure that there's a notice to that effect in the README when I'm ready to release 7.0.0 :+1:.

Anyway, let me know if you run into any other issues, I'll do what I can to help out.
