### ISSUE TITLE
ES6: Class constructor Chunk cannot be invoked without 'new'

### ISSUE THREAD

**Issue by SET001** [SierraSoftworks/Iridium#39]
I was trying a simple example code: 

```
interface ChunkDocument{
	_id?: string
  name: string
}

@Index({ name: 1 })
@Collection('chunks')
class Chunk extends Instance<ChunkDocument, Chunk> implements ChunkDocument{
	@ObjectID _id: string;
  @Property(/^.+$/)
  name: string;
}

class MyDatabase extends Core {
	Chunks = new Model<ChunkDocument, Chunk>(this, Chunk);
  // Houses = new Model<HouseDocument, House>(this, House);
}


var myDb = new MyDatabase({ database: 'avalon' });
myDb.connect().then(()=>{
	console.log("Database connected");
	myDb.Chunks.find().forEach((chunk: Chunk)=>{
 		console.log("===>" + chunk._id + "  " + chunk.name);
	 	myDb.close();
	 })
});	
```

and if I compile it with `"target": "es6"` in `tsconfig.json` then I got this error on runtime:

```
Unhandled rejection TypeError: Class constructor Chunk cannot be invoked without 'new'
    at new ModelSpecificInstance.constructor (/home/set/www/avalon/server/node_modules/iridium/dist/lib/ModelSpecificInstance.js:18:22)
    at ModelHelpers.wrapDocument (/home/set/www/avalon/server/node_modules/iridium/dist/lib/ModelHelpers.js:35:16)
    at /home/set/www/avalon/server/node_modules/iridium/dist/lib/Model.js:316:137
    at /home/set/www/avalon/server/node_modules/iridium/dist/lib/ModelHandlers.js:33:31
    at tryCatcher (/home/set/www/avalon/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/set/www/avalon/server/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/set/www/avalon/server/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/set/www/avalon/server/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/set/www/avalon/server/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/set/www/avalon/server/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/set/www/avalon/server/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

```

**Comment by SPARTAN563** [comment]
Hi there Konstantin,

I'll take a look at this today, but it would also be very helpful for me if you could send over the versions you're currently working with:

```
node --version
npm --version
npm ls
```

Thanks :+1:

**Comment by SET001** [comment]
set@set:~/www/avalon/server$ node --version
v6.2.1
set@set:~/www/avalon/server$ npm --version
3.9.3
set@set:~/www/avalon/server$ npm ls
avalon_server@0.1.0 /home/set/www/avalon/server
├─┬ gulp@4.0.0-alpha.2 (git://github.com/gulpjs/gulp.git#d60883ad911b37984b7a8f834092ea7e1aded7dc)
│ ├─┬ glob-watcher@3.0.0
│ │ ├─┬ async-done@1.2.0
│ │ │ ├── end-of-stream@1.1.0
│ │ │ ├── next-tick@0.2.2
│ │ │ ├─┬ once@1.3.3
│ │ │ │ └── wrappy@1.0.1
│ │ │ └── stream-exhaust@1.0.1
│ │ ├─┬ chokidar@1.5.0
│ │ │ ├── anymatch@1.3.0
│ │ │ ├── async-each@1.0.0
│ │ │ ├── UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
│ │ │ ├── glob-parent@2.0.0
│ │ │ ├─┬ is-binary-path@1.0.1
│ │ │ │ └── binary-extensions@1.4.0
│ │ │ ├─┬ is-glob@2.0.1
│ │ │ │ └── is-extglob@1.0.0
│ │ │ ├── path-is-absolute@1.0.0
│ │ │ └─┬ readdirp@2.0.0
│ │ │   ├─┬ minimatch@2.0.10
│ │ │   │ └─┬ brace-expansion@1.1.4
│ │ │   │   ├── balanced-match@0.4.1
│ │ │   │   └── concat-map@0.0.1
│ │ │   └─┬ readable-stream@2.1.2
│ │ │     └── isarray@1.0.0
│ │ ├─┬ lodash.assignwith@4.0.7
│ │ │ ├── lodash.keys@4.0.7
│ │ │ └── lodash.rest@4.0.3
│ │ └── lodash.debounce@4.0.6
│ ├─┬ gulp-cli@1.2.1
│ │ ├─┬ fancy-log@1.2.0
│ │ │ └── time-stamp@1.0.1
│ │ ├─┬ gulplog@1.0.0
│ │ │ └── glogg@1.0.0
│ │ ├── interpret@1.0.1
│ │ ├─┬ liftoff@2.2.1
│ │ │ ├── extend@2.0.1
│ │ │ ├─┬ findup-sync@0.3.0
│ │ │ │ └── glob@5.0.15
│ │ │ ├── flagged-respawn@0.3.2
│ │ │ ├── rechoir@0.6.2
│ │ │ └── resolve@1.1.7
│ │ ├─┬ lodash.sortby@4.5.0
│ │ │ ├── lodash._baseeach@4.1.3
│ │ │ ├── lodash._baseflatten@4.2.1
│ │ │ └─┬ lodash._baseiteratee@4.7.0
│ │ │   └─┬ lodash._stringtopath@4.8.0
│ │ │     └── lodash._basetostring@4.12.0
│ │ ├─┬ matchdep@1.0.1
│ │ │ ├─┬ micromatch@2.3.8
│ │ │ │ ├─┬ arr-diff@2.0.0
│ │ │ │ │ └── arr-flatten@1.0.1
│ │ │ │ ├── array-unique@0.2.1
│ │ │ │ ├─┬ braces@1.8.4
│ │ │ │ │ ├─┬ expand-range@1.8.2
│ │ │ │ │ │ └─┬ fill-range@2.2.3
│ │ │ │ │ │   ├── is-number@2.1.0
│ │ │ │ │ │   ├── randomatic@1.1.5
│ │ │ │ │ │   └── repeat-string@1.5.4
│ │ │ │ │ ├── preserve@0.2.0
│ │ │ │ │ └── repeat-element@1.1.2
│ │ │ │ ├─┬ expand-brackets@0.1.5
│ │ │ │ │ └── is-posix-bracket@0.1.1
│ │ │ │ ├── extglob@0.3.2
│ │ │ │ ├── filename-regex@2.0.0
│ │ │ │ ├─┬ kind-of@3.0.3
│ │ │ │ │ └── is-buffer@1.1.3
│ │ │ │ ├── normalize-path@2.0.1
│ │ │ │ ├─┬ object.omit@2.0.0
│ │ │ │ │ ├─┬ for-own@0.1.4
│ │ │ │ │ │ └── for-in@0.1.5
│ │ │ │ │ └── is-extendable@0.1.1
│ │ │ │ ├─┬ parse-glob@3.0.4
│ │ │ │ │ ├── glob-base@0.3.0
│ │ │ │ │ └── is-dotfile@1.0.2
│ │ │ │ └─┬ regex-cache@0.4.3
│ │ │ │   ├── is-equal-shallow@0.1.3
│ │ │ │   └── is-primitive@2.0.0
│ │ │ └── stack-trace@0.0.9
│ │ ├── mute-stdout@1.0.0
│ │ ├── pretty-hrtime@1.0.2
│ │ ├─┬ semver-greatest-satisfied-range@1.0.0
│ │ │ ├── semver@4.3.6
│ │ │ └── semver-regex@1.0.0
│ │ ├─┬ tildify@1.2.0
│ │ │ └── os-homedir@1.0.1
│ │ ├─┬ v8flags@2.0.11
│ │ │ └── user-home@1.1.1
│ │ ├─┬ wreck@6.3.0
│ │ │ ├── boom@2.10.1
│ │ │ └── hoek@2.16.3
│ │ └─┬ yargs@3.32.0
│ │   ├── camelcase@2.1.1
│ │   ├─┬ cliui@3.2.0
│ │   │ └── wrap-ansi@2.0.0
│ │   ├── decamelize@1.2.0
│ │   ├─┬ os-locale@1.4.0
│ │   │ └─┬ lcid@1.0.0
│ │   │   └── invert-kv@1.0.0
│ │   ├─┬ string-width@1.0.1
│ │   │ ├─┬ code-point-at@1.0.0
│ │   │ │ └── number-is-nan@1.0.0
│ │   │ └── is-fullwidth-code-point@1.0.0
│ │   ├── window-size@0.1.4
│ │   └── y18n@3.2.1
│ ├─┬ undertaker@0.15.0
│ │ ├─┬ bach@0.5.0
│ │ │ ├─┬ async-settle@0.2.1
│ │ │ │ └─┬ async-done@0.4.0
│ │ │ │   └── end-of-stream@0.1.5
│ │ │ ├─┬ lodash.filter@4.4.0
│ │ │ │ └── lodash._basefilter@4.0.1
│ │ │ ├── lodash.foreach@4.3.0
│ │ │ ├─┬ lodash.initial@4.0.4
│ │ │ │ └── lodash._baseslice@4.0.0
│ │ │ ├── lodash.last@3.0.0
│ │ │ └── now-and-later@0.0.6
│ │ ├─┬ es6-weak-map@2.0.1
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.11
│ │ │ ├── es6-iterator@2.0.0
│ │ │ └── es6-symbol@3.0.2
│ │ ├─┬ last-run@1.1.0
│ │ │ ├── default-resolution@1.0.1
│ │ │ └─┬ es6-weak-map@1.0.2
│ │ │   ├── es6-iterator@0.1.3
│ │ │   └── es6-symbol@2.0.1
│ │ ├─┬ lodash.defaults@4.0.1
│ │ │ └─┬ lodash.assigninwith@4.0.7
│ │ │   └── lodash.keysin@4.1.4
│ │ ├── lodash.flatten@4.2.0
│ │ ├── lodash.map@4.4.0
│ │ ├─┬ lodash.reduce@4.4.0
│ │ │ └── lodash._basereduce@3.0.2
│ │ └── undertaker-registry@1.0.0
│ └─┬ vinyl-fs@2.4.3
│   ├─┬ duplexify@3.4.3
│   │ ├── end-of-stream@1.0.0
│   │ └─┬ readable-stream@2.1.2
│   │   └── isarray@1.0.0
│   ├─┬ glob-stream@5.3.2
│   │ ├── extend@3.0.0
│   │ ├─┬ glob@5.0.15
│   │ │ ├── inflight@1.0.4
│   │ │ └── minimatch@3.0.0
│   │ ├─┬ ordered-read-streams@0.3.0
│   │ │ ├── is-stream@1.1.0
│   │ │ └─┬ readable-stream@2.1.2
│   │ │   └── isarray@1.0.0
│   │ ├─┬ through2@0.6.5
│   │ │ └── readable-stream@1.0.34
│   │ ├─┬ to-absolute-glob@0.1.1
│   │ │ └── extend-shallow@2.0.1
│   │ └─┬ unique-stream@2.2.1
│   │   └─┬ json-stable-stringify@1.0.1
│   │     └── jsonify@0.0.0
│   ├── graceful-fs@4.1.4
│   ├─┬ gulp-sourcemaps@1.6.0
│   │ └── convert-source-map@1.2.0
│   ├── is-valid-glob@0.3.0
│   ├─┬ lazystream@1.0.0
│   │ └─┬ readable-stream@2.1.2
│   │   └── isarray@1.0.0
│   ├─┬ lodash.isequal@4.2.0
│   │ └── lodash._root@3.0.1
│   ├─┬ merge-stream@1.0.0
│   │ └─┬ readable-stream@2.1.2
│   │   └── isarray@1.0.0
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├── object-assign@4.1.0
│   ├─┬ readable-stream@2.1.2
│   │ ├── isarray@1.0.0
│   │ ├── process-nextick-args@1.0.7
│   │ └── util-deprecate@1.0.2
│   ├─┬ strip-bom@2.0.0
│   │ └── is-utf8@0.2.1
│   ├─┬ strip-bom-stream@1.0.0
│   │ └── first-chunk-stream@1.0.0
│   ├── through2-filter@2.0.0
│   ├── vali-date@1.0.0
│   └─┬ vinyl@1.1.1
│     ├── clone@1.0.2
│     └── clone-stats@0.0.1
├─┬ gulp-jasmine@2.3.0
│ ├── arrify@1.0.1
│ ├─┬ gulp-util@3.0.7
│ │ ├── array-differ@1.0.0
│ │ ├── array-uniq@1.0.2
│ │ ├── beeper@1.1.0
│ │ ├─┬ dateformat@1.0.12
│ │ │ ├── get-stdin@4.0.1
│ │ │ └─┬ meow@3.7.0
│ │ │   ├── camelcase-keys@2.1.0
│ │ │   ├─┬ loud-rejection@1.3.0
│ │ │   │ ├── array-find-index@1.0.1
│ │ │   │ └── signal-exit@2.1.2
│ │ │   ├── map-obj@1.0.1
│ │ │   ├─┬ normalize-package-data@2.3.5
│ │ │   │ ├── hosted-git-info@2.1.4
│ │ │   │ ├─┬ is-builtin-module@1.0.0
│ │ │   │ │ └── builtin-modules@1.1.1
│ │ │   │ └─┬ validate-npm-package-license@3.0.1
│ │ │   │   ├─┬ spdx-correct@1.0.2
│ │ │   │   │ └── spdx-license-ids@1.2.1
│ │ │   │   └─┬ spdx-expression-parse@1.0.2
│ │ │   │     └── spdx-exceptions@1.0.4
│ │ │   ├─┬ read-pkg-up@1.0.1
│ │ │   │ ├─┬ find-up@1.1.2
│ │ │   │ │ └── path-exists@2.1.0
│ │ │   │ └─┬ read-pkg@1.1.0
│ │ │   │   ├─┬ load-json-file@1.1.0
│ │ │   │   │ └── pify@2.3.0
│ │ │   │   └── path-type@1.1.0
│ │ │   ├─┬ redent@1.0.0
│ │ │   │ └── strip-indent@1.0.1
│ │ │   └── trim-newlines@1.0.0
│ │ ├─┬ has-gulplog@0.1.0
│ │ │ └── sparkles@1.0.0
│ │ ├── lodash._reescape@3.0.0
│ │ ├── lodash._reevaluate@3.0.0
│ │ ├── lodash._reinterpolate@3.0.0
│ │ ├─┬ lodash.template@3.6.2
│ │ │ ├── lodash._basecopy@3.0.1
│ │ │ ├── lodash._basetostring@3.0.1
│ │ │ ├── lodash._basevalues@3.0.0
│ │ │ ├── lodash._isiterateecall@3.0.9
│ │ │ ├── lodash.escape@3.2.0
│ │ │ ├─┬ lodash.keys@3.1.2
│ │ │ │ ├── lodash._getnative@3.9.1
│ │ │ │ ├── lodash.isarguments@3.0.8
│ │ │ │ └── lodash.isarray@3.0.4
│ │ │ ├── lodash.restparam@3.6.1
│ │ │ └── lodash.templatesettings@3.1.1
│ │ ├─┬ multipipe@0.1.2
│ │ │ └─┬ duplexer2@0.0.2
│ │ │   └── readable-stream@1.1.14
│ │ ├── object-assign@3.0.0
│ │ ├── replace-ext@0.0.1
│ │ └── vinyl@0.5.3
│ ├─┬ jasmine@2.4.1
│ │ ├── exit@0.1.2
│ │ ├─┬ glob@3.2.11
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.7.3
│ │ │   └── sigmund@1.0.1
│ │ └── jasmine-core@2.4.1
│ ├─┬ jasmine-terminal-reporter@1.0.1
│ │ ├─┬ indent-string@2.1.0
│ │ │ └─┬ repeating@2.0.1
│ │ │   └── is-finite@1.0.1
│ │ └── pluralize@1.2.1
│ └─┬ through2@2.0.1
│   └─┬ readable-stream@2.0.6
│     └── isarray@1.0.0
├─┬ gulp-typescript@2.13.4
│ ├── source-map@0.5.6
│ └── typescript@1.8.10
├── inversify@2.0.0-beta.8
├── inversify-dts@1.0.5
├─┬ iridium@7.0.0-alpha.7
│ ├── bluebird@3.3.5
│ ├── lodash@4.13.1
│ └── skmatc@1.2.0
├─┬ jasmine-spec-reporter@2.4.0
│ └── colors@1.1.2
├─┬ mongodb@2.1.18
│ ├── es6-promise@3.0.2
│ ├─┬ mongodb-core@1.3.18
│ │ ├── bson@0.4.23
│ │ └─┬ require_optional@1.0.0
│ │   ├── resolve-from@2.0.0
│ │   └── semver@5.1.0
│ └─┬ readable-stream@1.0.31
│   ├── core-util-is@1.0.2
│   ├── inherits@2.0.1
│   ├── isarray@0.0.1
│   └── string_decoder@0.10.31
├── mongoose@4.4.20 extraneous
├── mongorito@2.1.2 extraneous
├── node-gameloop@0.1.0
├── q@1.4.1
├── reflect-metadata@0.1.3
├─┬ socket.io@1.4.6
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ engine.io@1.6.9
│ │ ├─┬ accepts@1.1.4
│ │ │ ├─┬ mime-types@2.0.14
│ │ │ │ └── mime-db@1.12.0
│ │ │ └── negotiator@0.4.9
│ │ ├── base64id@0.1.0
│ │ ├─┬ engine.io-parser@1.2.4
│ │ │ ├── after@0.8.1
│ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ ├── blob@0.0.4
│ │ │ ├── has-binary@0.1.6
│ │ │ └── utf8@2.1.0
│ │ └─┬ ws@1.0.1
│ │   ├── options@0.0.6
│ │   └── ultron@1.0.2
│ ├── has-binary@0.1.7
│ ├─┬ socket.io-adapter@0.4.0
│ │ └─┬ socket.io-parser@2.2.2
│ │   ├── debug@0.7.4
│ │   └── json3@3.2.6
│ ├─┬ socket.io-client@1.4.6
│ │ ├── backo2@1.0.2
│ │ ├── component-bind@1.0.0
│ │ ├── component-emitter@1.2.0
│ │ ├─┬ engine.io-client@1.6.9
│ │ │ ├── component-inherit@0.0.3
│ │ │ ├── has-cors@1.1.0
│ │ │ ├── parsejson@0.0.1
│ │ │ ├── parseqs@0.0.2
│ │ │ ├── xmlhttprequest-ssl@1.5.1
│ │ │ └── yeast@0.1.2
│ │ ├── indexof@0.0.1
│ │ ├── object-component@0.0.3
│ │ ├─┬ parseuri@0.0.4
│ │ │ └─┬ better-assert@1.0.2
│ │ │   └── callsite@1.0.0
│ │ └── to-array@0.1.4
│ └─┬ socket.io-parser@2.2.6
│   ├── benchmark@1.0.0
│   ├── component-emitter@1.1.2
│   └── json3@3.3.2
└─┬ typings@0.8.1
  ├── any-promise@1.3.0
  ├── archy@1.0.0
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.0.0
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ columnify@1.5.4
  │ └─┬ wcwidth@1.0.0
  │   └── defaults@1.0.3
  ├── listify@1.0.0
  ├── minimist@1.2.0
  ├─┬ typings-core@0.3.1
  │ ├─┬ configstore@2.0.0
  │ │ ├─┬ dot-prop@2.4.0
  │ │ │ └── is-obj@1.0.1
  │ │ ├── os-tmpdir@1.0.1
  │ │ ├── osenv@0.1.3
  │ │ ├── uuid@2.0.2
  │ │ ├─┬ write-file-atomic@1.1.4
  │ │ │ ├── imurmurhash@0.1.4
  │ │ │ └── slide@1.1.6
  │ │ └── xdg-basedir@2.0.0
  │ ├── detect-indent@4.0.0
  │ ├─┬ has@1.0.1
  │ │ └── function-bind@1.1.0
  │ ├─┬ invariant@2.2.1
  │ │ └─┬ loose-envify@1.1.0
  │ │   └── js-tokens@1.0.3
  │ ├─┬ is-absolute@0.2.5
  │ │ ├─┬ is-relative@0.2.1
  │ │ │ └─┬ is-unc-path@0.1.1
  │ │ │   └── unc-path-regex@0.1.2
  │ │ └── is-windows@0.1.1
  │ ├── lockfile@1.0.1
  │ ├─┬ make-error-cause@1.1.0
  │ │ └── make-error@1.1.1
  │ ├─┬ object.pick@1.1.2
  │ │ └─┬ isobject@2.1.0
  │ │   └── isarray@1.0.0
  │ ├─┬ parse-json@2.2.0
  │ │ └─┬ error-ex@1.3.0
  │ │   └── is-arrayish@0.2.1
  │ ├─┬ popsicle@5.0.1
  │ │ ├─┬ concat-stream@1.5.1
  │ │ │ ├─┬ readable-stream@2.0.6
  │ │ │ │ └── isarray@1.0.0
  │ │ │ └── typedarray@0.0.6
  │ │ ├─┬ form-data@0.2.0
  │ │ │ ├── async@0.9.2
  │ │ │ └─┬ combined-stream@0.0.7
  │ │ │   └── delayed-stream@0.0.5
  │ │ ├── methods@1.1.2
  │ │ └── tough-cookie@2.2.2
  │ ├─┬ popsicle-proxy-agent@1.0.0
  │ │ ├─┬ http-proxy-agent@1.0.0
  │ │ │ └─┬ agent-base@2.0.1
  │ │ │   └── semver@5.0.3
  │ │ └── https-proxy-agent@1.0.0
  │ ├── popsicle-retry@2.0.0
  │ ├── popsicle-status@1.0.2
  │ ├── promise-finally@2.2.0
  │ ├─┬ rc@1.1.6
  │ │ ├── deep-extend@0.4.1
  │ │ ├── ini@1.3.4
  │ │ └── strip-json-comments@1.0.4
  │ ├─┬ rimraf@2.5.2
  │ │ └── glob@7.0.3
  │ ├─┬ sort-keys@1.1.1
  │ │ └── is-plain-obj@1.1.0
  │ ├── string-template@1.0.0
  │ ├── thenify@3.2.0
  │ ├── throat@2.0.2
  │ ├─┬ touch@1.0.0
  │ │ └─┬ nopt@1.0.10
  │ │   └── abbrev@1.0.7
  │ └── zip-object@0.1.0
  ├─┬ update-notifier@0.6.3
  │ ├─┬ boxen@0.3.1
  │ │ ├── filled-array@1.1.0
  │ │ └── widest-line@1.0.0
  │ ├── is-npm@1.0.0
  │ ├─┬ latest-version@2.0.0
  │ │ └─┬ package-json@2.3.2
  │ │   ├─┬ got@5.6.0
  │ │   │ ├─┬ create-error-class@3.0.2
  │ │   │ │ └── capture-stack-trace@1.0.0
  │ │   │ ├─┬ duplexer2@0.1.4
  │ │   │ │ └─┬ readable-stream@2.1.2
  │ │   │ │   └── isarray@1.0.0
  │ │   │ ├── is-redirect@1.0.0
  │ │   │ ├── is-retry-allowed@1.0.0
  │ │   │ ├── lowercase-keys@1.0.0
  │ │   │ ├── node-status-codes@1.0.0
  │ │   │ ├─┬ pinkie-promise@2.0.1
  │ │   │ │ └── pinkie@2.0.4
  │ │   │ ├─┬ read-all-stream@3.1.0
  │ │   │ │ └─┬ readable-stream@2.1.2
  │ │   │ │   └── isarray@1.0.0
  │ │   │ ├─┬ readable-stream@2.1.2
  │ │   │ │ └── isarray@1.0.0
  │ │   │ ├── timed-out@2.0.0
  │ │   │ ├── unzip-response@1.0.0
  │ │   │ └─┬ url-parse-lax@1.0.0
  │ │   │   └── prepend-http@1.0.4
  │ │   └── registry-url@3.1.0
  │ └── semver-diff@2.1.0
  ├── wordwrap@1.0.0
  └── xtend@4.0.1

**Comment by SET001** [comment]
I should mention that first when I meat this issue I was using node v5.10.1 and then upgraded to 6.2.1
Also I think all this is not related to node or any or its' packages version. This is because in ES6 you can't run constructor like regular function, you should run it with `new`

```
    let constructor = function (doc: TDocument, isNew?: boolean, isPartial?: boolean) {
        instanceType.call(this, model, doc, isNew, isPartial);
    };

```

**Comment by SPARTAN563** [comment]
Hi Konstantin,

Sorry that this took a while, been one hell of a busy day and a rather tricky issue to work around. I've made the changes you see above which should rectify the problem for you and will release `7.0.0-alpha.8` just now with those included. Please let me know if you run into further issues or if this doesn't address the problems you're seeing.

Regards,
Benjamin

**Comment by SET001** [comment]
@SPARTAN563 appreciate you help, this release fixed a problem, Thanx a lot.
Also thanx for this awesome ODM. You're doing a good job!

**Comment by SET001** [comment]
seems like I should also recompile Iridium in ES6

**Comment by SPARTAN563** [comment]
I see, from my perspective it seems that anybody developing a new Node.js application will very probably be running on Node 4.x LTS and up, so let me quickly compile a version targetting ES6 and see what mileage we get out of it for tests etc. If that all looks good, then I'll strongly consider making Iridium 7 an ES6 only variant.

**Comment by SPARTAN563** [comment]
Hi Konstantin,

I've put out `7.0.0-alpha.9`, however please be aware that it is only tested, and intended to work correctly, on Node.js 6.x and up. Node.js 4.x LTS is unfortunately lacking support for the rest operator (`...args`) and as a result it will not function correctly unless you run Node.js with the `--harmony` flag set.

Other than that, it is now compiled to target ES6 and some improvements have been made to the build and deployment process.

**Comment by uMaxmaxmaximus** [comment]
thw same problem, a use babel

C:\localhost\ui-js\server\lib\list.js:36
        var _this = _possibleConstructorReturn(this, Object.getPrototypeOf(List).call(this, _db2.default, InstanceClass));
                                                                                 ^

TypeError: Class constructor Model cannot be invoked without 'new'

**Comment by uMaxmaxmaximus** [comment]
Iridium is extremely is crude thing

i will be use this https://www.arangodb.com
bye =)

**Comment by SPARTAN563** [comment]
Keep in mind that v7 is marked alpha for a reason, busy experimenting there to find better ways of solving those sorts of problems for everyone. Sorry to hear you're struggling and wish you the best of luck with ArangoDB.

In the mean time, would you be able to tell me whether you're compiling to ES6 or ES5 from Babel? I'm guessing you're compiling to ES5 and that's what is resulting in the issue - in which case I will need to try and find an alternative solution (perhaps feature detection).
