### ISSUE TITLE
In the Iridium present ideological error

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#44]
I write Iridium alternative, and I realized that something =)
In the Iridium present ideological error:

ORM is:

```javascript
class User extends Model {
  this.name // document field
  sayName(){ alert(this.name) } // model method
  statiс insert(){} // collection method
  statiс update(){} // collection method
}

and

let user = await User.add({name:ololo})
user.sayName()
```

No need class `UserS` just a `User` =)

transforms:
```javascript
class User {

  // from db document
  constructor(document){
    this.name = document.name
    this.date = new Date(document.date)
  }

  // to db document (call before save model in db)
  toDocument(){
    return {name: this.name, date: this.date.toString()}
  }

}
```

at least I do this ^ _ ^

Thus, javascript OOP, transparently reflected in the database. 
What do you think about this?

**Comment by SPARTAN563** [comment]
Hi Ivan,

It's certainly something I considered and a very elegant approach, Iridium's reason for adopting two classes (Model and Instance) is to allow you to swap out the Instance implementation at any point (whether for performance, enhancing the API or if you want to do some different validation logic etc).

The other little thing to keep in mind is that you need to hold references to a bit of configuration and database stuff usually (open DB connection, schema, validators etc) - which  quickly pollutes the `Model` class and steals property names from developers down the line (if they use the same property name they can quickly get strange results). You can, of course, work around this by prefixing your property names with something like `$connection` (which is an invalid name in the MongoDB world, so people shouldn't overwrite them by accident).

**Comment by uMaxmaxmaximus** [comment]
I think the to memorize 2 methods "save" and "remove", will not be much of a problem for the user =))

```javascript
class Model {
  save(){} // call Model.update(this)
  remove(){} // call Model.remove(this)
}
```
