### ISSUE TITLE
which version of node.js do I need to run the latest release? 

### ISSUE THREAD

**Issue by vsuhanov** [SierraSoftworks/Iridium#46]
Hello,

I am currently running node version `v4.4.7` and if I run the app with iridium I get either

```
.../node_modules/iridium/dist/lib/Model.js:205
    get(...args) {
        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17) 
```

or if I run with `--harmony` flag: 

```
.../node_modules/iridium/dist/lib/Instance.js:28
    constructor(model, document, isNew = true, isPartial = false) {
```

So basically the rest parameter works with only if I enable harmony features, the second one does not work at all. Should I update my node.js to later versions (I kind of prefer having LTS here but can update)? Or is there a version that compiles into ES5 perhaps?

**Comment by SPARTAN563** [comment]
Hi Vitaly,

The current stable version (6.7.0) should run without any issues on Node 4.x; however if you'd like to try out the 7.0.0-alpha versions (the latest being 7.0.0-alpha.15) then you'll need to make use of Node 6.x and an up to date version of NPM (with support for namespacing).

Aside from the usability enhancements, there shouldn't be any major reason to move away from 6.7.0 in production.
