### ISSUE TITLE
Ship .ts files on npm?

### ISSUE THREAD

**Issue by philkunz** [SierraSoftworks/Iridium#50]
I noticed that Iridium ships the .ts files with the npm package, not just d.ts files. Is this intended?

By default typescript compiler picks up those .ts files if not properly excluded which may lead to unexpected behaviour.

**Comment by SPARTAN563** [comment]
That's curious, the `.npmignore` file is set to ignore all the .ts files (well, technically everything but the dist folder and some other specific files) on `7.0.0-dev`. Master on the other hand had that decision made for a reason, insofar as there aren't `d.ts` files there.

**Comment by philkunz** [comment]
Ah, you are right, I had the release branch installed 6.7.0.

Sorry for the confusion.
