### ISSUE TITLE
Advanced data type

### ISSUE THREAD

**Issue by AntoineABI** [SierraSoftworks/Iridium#54]
Hi,

sorry to bother but I am struggling to find out how to use some mongodb native data type like GeoJSON, Polygon etc... I did not find out in the wiki.
It will be great to have some examples or maybe it is not possible?

Greatings

**Comment by SPARTAN563** [comment]
Hey Antoine,

Depending on your use case, there are two approaches you can take...

### TypeScript Heavy
In this case you're relying on TypeScript to handle your "validation" but it does give you the ability to allow various different GeoJSON types in the same field without losing that type validation accuracy. This would probably work best if you don't know the kind of GeoJSON primitive that you're going to get or have to use more than one and switch between at runtime.

```typescript
type GeoJSON = GeoJSONPoint | GeoJSONLineString; //... and whatever other types you use

interface GeoJSONPrimitive {
  type: string;
}

interface GeoJSONPoint {
  type: "Point";
  coordinates: number[];
}

function isGeoJSONPoint(value: GeoJSONPrimitive): value is GeoJSONPoint {
  return value.type === "Point";
}

interface GeoJSONLineString {
  type: "LineString";
  coordinates: number[][];
}

function isGeoJSONLineString (value: GeoJSONPrimitive): value is GeoJSONLineString {
  return value.type === "LineString";
}

const GeoJSONSchema = {
  type: /^(Point|LineString)$/,
  coordinates: { $type: [true], $required: false }
}
```

```typescript
interface MyInstanceDoc {
  _id?: string;

  feature: GeoJSON;
}

class MyInstance extends Iridium.Instance<MyInstanceDoc, MyInstance> {
  @Iridium.ObjectID
  _id: string;

  @Iridium.Property(GeoJSONSchema)
  feature: GeoJSON;
}
```

### More Restrictive, Schema Heavy
In this case, you're taking advantage of Iridium's schema engine a bit more to ensure that what you send through to the DB is in the correct format (though a geo index in MongoDB will do the same for you). It's also nice in that you don't need to check what type of GeoJSON object a field represents (using the `isGeoJSONtype()` function) before you can access all of its properties.

```typescript
const GeoJSONPointSchema = {
  type: /^Point$/,
  coordinates: [Number,2,2]
}

interface GeoJSONPoint {
  type: "Point",
  coordinates: number[];
}

const GeoJSONLineStringSchema = {
  type: /^Point$/,
  coordinates: [[Number,2,2]]
}

interface GeoJSONLineString {
  type: "LineString",
  coordinates: number[][];
}
```

```typescript
interface MyInstanceDoc {
  _id?: string;

  position: GeoJSONPoint;
  trail: GeoJSONLineString;
}

class MyInstance extends Iridium.Instance<MyInstanceDoc, MyInstance> {
  @Iridium.ObjectID
  _id: string;

  @Iridium.Property(GeoJSONPointSchema)
  position: GeoJSONPoint;
  
  @Iridium.Property(GeoJSONLineStringSchema)
  trail: GeoJSONLineString;
}
```
