### ISSUE TITLE
Update a single document with the _id

### ISSUE THREAD

**Issue by ChrLipp** [SierraSoftworks/Iridium#55]
I want to update a single document with

        this.model.update(_id, item);

However I receive from MongoDB

        multi update only works with $ operators

I even receive the same error when I call

        this.model.update(_id, item, { multi: false });

How would I update a single document? When the id is given why is Iridium using the multi update mode?

Thank's for your work, regards,
Christian

**Comment by SPARTAN563** [comment]
Ah, I actually don't think I've covered this use case (I tend to prefer atomic updates rather than replacements, just for the added safety that introduces in concurrent environments). The `{ multi: false }` case should have solved the problem for you, so let me take a look and put together a repro case.

Regards,
Benjamin

**Comment by SPARTAN563** [comment]
That should fix the problem, I'm just waiting for the Travis tests to pass (just in case there's something on my local machine which differs) and then I'll publish it at v7.0.1. Sorry about the inconvenience.

**Comment by SPARTAN563** [comment]
Version 7.0.1 is now released, you should be able to update using `npm install iridium@7.0.1`.

Feel free to re-open this if you see the problem manifest again, or aren't able to get the latest release working correctly.

**Comment by ChrLipp** [comment]
Thanks for your quick response!

When I perform an update now I receive from MongoDB:

    The _id field cannot be changed from {_id: ObjectId('58198d8d772afb7be2e31c8c')} to {_id: \"58198d8d772afb7be2e31c8c\"}.

When I remove the _id field from the json payload I get a

   E11000 duplicate key error collection: collecton.Document index: name_1 dup key: { : \"Unique string\" }

since I have a unique index on the field. So I am still not able to update the single document.

**Comment by SPARTAN563** [comment]
That's particularly odd, can you try not removing the `_id` field and instead exposing it as an `ObjectId`? The easiest way to do this (if you already have a document from Iridium) is to use `item.document`.

```typescript
model.findOne().then(item => model.update(item._id, item.document, { multi: false }))
```

**Comment by SPARTAN563** [comment]
Alternatively, if the `item` you have wasn't sourced from Iridium (you got it over an API or some other source) then you can convert `_id` using `Iridium.toObjectID(item._id)`

**Comment by ChrLipp** [comment]
I am building a CRUD app with [inversify-express-utils](https://github.com/inversify/inversify-express-utils) and Iridium and therefor receive the item data via a PUT.

Your second recommendation worked: I used

        this.model.update(toObjectID(_id), item, { multi: false });

and additionally I had to remove the `_id` from the item.

**Comment by SPARTAN563** [comment]
Sorry that I'm only getting back to you now - it's been chaotic on my side these past few days.

I've made some fixes which should now result in it returning the correct value (coming in 7.0.2), I'll also see what I can do about #56 for you.

**Comment by ChrLipp** [comment]
The result code works now, thanks a lot. To summarize I have to use:

    this.model.update(toObjectID(_id), item, { multi: false });

and additionally I had to remove the _id from the item, otherwise the old error occurred.

**Comment by SPARTAN563** [comment]
Glad to hear it's working, you'll probably also find that converting the `item._id` to an ObjectID would fix your problems as well (if the unit tests are anything to go by).

```
item._id = Iridium.toObjectID(item._id);
this.model.update(item._id, item, { multi: false });
```

**Comment by ChrLipp** [comment]
Thanks for your comment, works great!
