### ISSUE TITLE
Typings for cursor missing

### ISSUE THREAD

**Issue by ChrLipp** [SierraSoftworks/Iridium#56]
`find`returns a `Cursor` which is not included in your exported typings (`iridium.d.ts`).

**Comment by SPARTAN563** [comment]
Very odd, I'm about 99.9% certain that it's there and working (just checked on my local machine), can you quickly confirm the versions of Node.js, TypeScript and Iridium that you're using so I can try and narrow it down?

**Comment by ChrLipp** [comment]
Sorry, I updated to 7.0.1 and cannot reproduce it myself even if there was no change regarding the typings between 7.0.0 and 7.0.1.

So sorry for the wrong issue and thanks for your work!

**Comment by SPARTAN563** [comment]
Ah, yeah it doesn't export the Cursor type as you aren't meant to instantiate it yourself, but the type information should be included in the definitions nonetheless, so you should be able to access methods on `Model.find()` without problems.

**Comment by ChrLipp** [comment]
I have a repository and wanted to avoid the `any` in the definition:

    public retreiveAll: (() => Promise<Cursor>) = () => {
        return Promise.resolve(this.model.find());
    }

Of course I am able to use the result, but I can't define the signature of the function.

**Comment by SPARTAN563** [comment]
I'm rather apprehensive about polluting Iridium's external API with the class definition for a cursor, and I also don't particularly want to maintain a separate interface for something that is already covered by the class docs...

That being said, TypeScript should be able to infer the correct signature automatically, the only possible issue could be if you're wanting to build a fully self-contained type definition, in which case there'll obviously not be the required data...

On an unrelated note, the API you've got there (where a promise resolves with the cursor) isn't necessary - a cursor represents a synchronously created query object and doesn't dispatch to the DB until one of its result methods (`next`, `toArray`, `each` etc) is called - so you're adding the overhead of a Promise for effectively no gain, it'd be like `() => Promise.resolve(1)`. Mind you, that may just be the result of how your API framework handles stuff, in which case don't mind me :smile:

**Comment by ChrLipp** [comment]
This is ok for me.

TypeScript isn't really able to infer the type therefor I tried to add it, but I stick with `any`. I use it in my controllers to stream the result to the client:

    export function iridiumCursor2JsonResponse(cursor: any, response: Response): void {
        let isFirst: boolean = true;
        response.set('Content-Type', 'application/json');
    
        cursor.cursor
            .on('data', function onData(data) {
                if (isFirst) {
                    response.write('[');
                    isFirst = false;
                }
                else {
                    response.write(', ');
                }
                response.write(JSON.stringify(data));
            })
            .on('end', function onEnd() {
                if (!isFirst) {
                    response.end(']');
                }
                else {
                    response.end();
                }
            });
    }

I know that the line

     return Promise.resolve(this.model.find());

does to much, the reason for me was to convert from Bluebird data type to standard Promise data type.

So it is fine for me when you close the issue. Thanks for your work.
