### ISSUE TITLE
Optional JSON field

### ISSUE THREAD

**Issue by ChrLipp** [SierraSoftworks/Iridium#57]
I am not sure if this is a support question. Do you monitor Stackoverflow for future support requests?
What I want is to store an optional JSON in a document. The structure of the JSON is unknown.

	@Property(String)
	public field: string;

did not work since the data is optional. I received a 

	Expected field to be a defined non-null value but got undefined instead

The next thing I tried was

	@Property({ asType: String, required: false })
	public field: String;

However I still receive the error message above.

So I have two questions:
- how would I model an optional field
- what is the best data type to store JSON (in my case I chose string)

Kind regards, Christian

**Comment by SPARTAN563** [comment]
Hi Christian,

The best way to store a JSON value will depend on whether you intend on storing a JSON object or just a JSON value (i.e. `{}|any[]|string|boolean|number`).

### Storing a JSON Value

```typescript
@Property(true)
public field: any;

@Property(false)
public opt_field: any;
```

### Storing a JSON Object
```typescript
@Property(Object)
public field: Object;

@Property(Object, false)
public opt_field: Object;

@Property({ $type: Object, $required: false })
public explicit_field: Object;
```

In most cases the best datatype to store "JSON" in is in its raw object form, this allows MongoDB to query on the contents of the JSON effectively, provides storage benefits (numbers and dates are stored in a compact binary representation) and is generally the idiomatic approach to take.

**Comment by ChrLipp** [comment]
Thanks for your effort!
