### ISSUE TITLE
Support for SQL?

### ISSUE THREAD

**Issue by pyros2097** [SierraSoftworks/Iridium#60]
I was looking at orms to support postgres database and nothing seems good enough for me so I thought as iridium already has a really good model layer wouldn't it be easy to add support for SQL databases as only the serialization and row fetching part has to be implemented. Is is possible to add that feature or should a new ORM specifically be created for this purpose.

**Comment by SPARTAN563** [comment]
In theory I suppose it would be possible to apply the same design to a SQL ORM, however Iridium itself is very strongly tied to MongoDB in terms of its API and there are certain things which we explicitly avoid making accessible (joins) to encourage people to apply performant schema design principles.

RDBMSes on the other hand require this sort of functionality (1-Many join support at an absolute minimum, ideally abstractions for 1-1 and M-M joins as well). In addition to that, most RDBMSes require you to define your schema in-DB, requiring support for schema migrations and potentially schema-generation (for DB first) or init generation (for code-first).

As far as finding an ORM which suits your needs, I've heard great things about [Sequelize](http://docs.sequelizejs.com/en/v3/) and [Waterline](https://github.com/balderdashy/waterline) depending on what your usecase and preferences are. I was previously also a contributor to [orm](https://github.com/dresende/node-orm2) and it served its purpose well, however it lacks support for some advanced use cases and can be memory-heavy (it ensures that documents with ID equality are also returned with reference equality).

**Comment by pyros2097** [comment]
Thanks for the info I looked ad sequelize and waterline they are not typesafe like iridium and I have created a SQL ORM for go before without joins or migrations since I generally don't use joins and would prefer not to have that functionality. Anyways maybe I should just use mongo for now since using SQL is not a main concern. I guess iridium is mainly tied to mongo then.
