### ISSUE TITLE
Question: Optional substructure

### ISSUE THREAD

**Issue by ChrLipp** [SierraSoftworks/Iridium#67]
I have the following interface:

    export interface IUserDocument  {
        _id?: string;
        /** Specific data for user with Username/Password registration strategy */
        localUser?: {
            /** Hashed password */
            hashedPassword: string;
    
            /** Random Hash for email notification */
            randomHash?: string;
        };
    
        /** Specific data for user with Facebook registration strategy */
        facebookUser?: {
            /** Facebook internal id identificating the user */
            id: string;

            /** Just for the question */
            option?: string;
        };
    }

localUser and facebookUser are exclusive, so when one is given, the other one is not provided. When I provide a local user I want to guarantee that hashedPassword is set, while randomHash is optional. When I provide a facebook user I want to have id mandatory, while option is optional (sorry :-)).

How do I model this? When I use something like

    @Property({
        facebookId: {$type: String, $required: false}
    })
    public facebookUser?: {
        id: string;
    };

this feels wrong and I stil receive "Expected facebookUser to be a defined non-null value but got undefined instead". I want to have the whole facebookUser optional.

Thanks for your help!

**Comment by SPARTAN563** [comment]
Hey Christian,

You should be able to specify that a property itself is optional, there are two ways of doing this at the top level:

```typescript
@Property({
  facebookId: String
}, false)
```

```typescript
@Property({
  $required: false,
  $type: {
    facebookId: String
  }
})
```

The next part, where you want to validate that only one of those properties is present at a time, is a bit more complicated. I haven't actually modeled those kinds of cross-property validation relationships in Iridium's validation library so you'll probably need to use an `onSaving()` hook to enforce it.

```typescript
class XYZ extends Iridium.Model<XYZDoc, XYZ> {
  static onSaving(x: XYZ, changes: Iridium.Changes) {
    if(x.facebookUser && x.localUser) return Promise.reject(new Error("expected only one of ('facebookUser', 'localUser') to be set on this document"));
  }
}
```

Keep in mind, however, that if you use the `Model.update(...)` method to change this document, that validator won't be fired, so you'll want to make sure that all your changes happen via instances you've retrieved from Iridium.

You may also want to add an `onCreating()` hook to prevent it from being created initially with both of those fields set, depending on your use case.

```typescript
class XYZ extends Iridium.Model<XYZDoc, XYZ> {
  static onCreating(x: XYZDoc) {
    if(x.facebookUser && x.localUser) return Promise.reject(new Error("expected only one of ('facebookUser', 'localUser') to be set on this document"));
  }
}
```

**Comment by ChrLipp** [comment]
This helped a lot! Thanks for your effort!
