### ISSUE TITLE
Documentation stats wrong 

### ISSUE THREAD

**Issue by Kanti** [SierraSoftworks/Iridium#69]
````ts
@Iridium.Validate('myValidator', x => x === 42)
````

Error:(12, 29) TS2345:Argument of type '(this: { validator: IValidationHandler; skmatc: Skmatc; fail(message?: string | undefined): Resul...' is not assignable to parameter of type 'IValidationHandler'.
  Type 'boolean' is not assignable to type 'Result'.

**Comment by SPARTAN563** [comment]
Thanks for bringing this discrepancy to my attention, I'll only be able to address it early next week but please let me know if you haven't managed to figure out how to actually declare validations and would like some help.

**Comment by Kanti** [comment]
````ts
@Iridium.Validate( 'myValidator', function ( schema: any, data: any, path: string ) {
  return this.assert( data === 42 );
} )
````
Worked for me.

**Comment by jsdream** [comment]
Hi Benjamin!

Did you have an opportunity to take a look at this issue?

**Comment by SPARTAN563** [comment]
Hi Vladyslav, yeah I'm actually planning on tackling both this and docs for #70 this evening - I just need to try and make sure the docs build correctly, sometimes a bit of a hassle when I update TypeScript.

**Comment by SPARTAN563** [comment]
Hi @Kanti, do you mind reviewing the updates to the docs - specifically the [README](https://github.com/SierraSoftworks/Iridium/blob/master/README.md) - and letting me know the changes clarify things for you satisfactorily?

One little note, you don't need to specify the types for the parameters on your decorator function - TypeScript will infer them correctly and also give you type suggestions for the `this` context, making it relatively easy to discover what functions are available for you to use. I've updated the README example to remove those as well, as I'm sure it may lead to some confusion.

**Comment by Kanti** [comment]
Yes this clarifies it.

And thank you for your little note. 😉
