### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by davidhunt135** [SierraSoftworks/Iridium#71]
I have a working project which I have not used @types in before. After installing Iridium it will still build but as soon as I add a reference to use it then the build breaks. I am using tsc v 2.2.1 and targeting es6. 

Am I doing something wrong?

Here is my tsconfig.json

```
{
    "compilerOptions": {
	"target": "es6",
        "module": "commonjs",
	"removeComments": true,
	"declaration": false,
	"noImplicitAny": false,
	"noEmitOnError": false,
        "pretty": false,
	"rootDir": "./",
	"forceConsistentCasingInFileNames": true,
	"version": true,
        "sourceMap": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "strictNullChecks": true,
        "noImplicitThis": true
	},
    "exclude": [
        "node_modules"
    ]
}
```

Error

`'\u001b[31m/**/node_modules/iridium/dist/lib/BSON.d.ts(3,44): \u001b[39merror TS1110: Type expected.' }`

Thanks, David

**Comment by davidhunt135** [comment]
It seems I was using an older version of gulp-typescript which wasn't using tsc 2.2.1. I have updated this and it now works.

**Comment by SPARTAN563** [comment]
Glad you managed to come right David, let me know if you run into anything else.
