### ISSUE TITLE
RxJS Friendlyness

### ISSUE THREAD

**Issue by Kaffiend** [SierraSoftworks/Iridium#72]
Instead of callbacks and promises what about rxjs observables etc. We could make a promise an observable easy enough, is there any issues or pitfalls working with iridium in rxjs? Most of our projects are ngrx based with electron.

**Comment by SPARTAN563** [comment]
Hi Ian,

I can't imagine any reason why you would struggle to make Iridium work well with observables - it uses a fully standards compliant Promise implementation and doesn't do any funny nonsense with them.

I do suppose the one case you might want to special case is cursors if you're looking for any kind of back-pressure support or wish to cascade certain functions through to the underlying cursor (such as `skip`) in the same way that LINQ does in C#.

Is there anything in particular that worries you or that you're afraid might trip you up on your project?

**Comment by Kaffiend** [comment]
Well, Its electron and angular with ngrx store and talks directly to mongo, no API calls. I was hoping to utilize the cursor in the exact way you mention. as well as maintain it in ngrx state, where pretty much everything is a stream. Currently im using the native node driver and its working ok, but it lacks structure that i feel iridium would give it.

**Comment by SPARTAN563** [comment]
I see, it sounds to me like your best bet is going to be creating your own cursor wrapper which uses the RxJS [`Observable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/create.md) to emit results for something like `toObservable()`. Again, I'm not sure how you'll get around the issue of back pressure (this would be a hot observable) but that is something you'd need to face regardless of whether you were using RxJS or not.

I'm somewhat averse to introducing extra code for every niche use case into Iridium's core, but let me know if you'd like a hand with putting together something which patches support for RxJS onto Iridium for your use case.

As for structure, it'll really depend on what you've put together right now. I personally find it much easier to work with Iridium thanks to all the type information it exposes as well as the features like validation and transforms, however I am obviously somewhat biased on that front. Frankly, if you've got a very simple application, even something as simple as Iridium might be overkill for it; and the MongoDB driver has improved in leaps and bounds recently, so it may be more than enough for your needs.

**Comment by Kaffiend** [comment]
I'm inclined to agree, it may be overkill. i think ill be better off for the time being to write my own abstractions.. Thank you for the insight!!
