### ISSUE TITLE
Replica Sets - Clusters MongoDB Atlas

### ISSUE THREAD

**Issue by Kaffiend** [SierraSoftworks/Iridium#77]
Is there an example im not seeing on configuring for replica sets and clusters like MongoDB Atlas?

**Comment by SPARTAN563** [comment]
Hi Kaffiend,

You should be able to specify them as part of the URL used to connect, something like:

```typescript
const core = new Iridium.Core("mongodb://server1,server2,server3/my_db")
```

Alternatively, if you're using the structured settings object, you can specify the servers like this ([docs](http://sierrasoftworks.github.io/Iridium/interfaces/configuration.html#hosts)):

```typescript
const core = new Iridium.Core({
  database: "my_db",
  hosts: [
    { address: "server1" },
    { address: "server2" },
    { address: "server3" }
  }
})
```

Let me know if you run into any issues with that or have further questions.

**Comment by Kaffiend** [comment]
I saw those but wasnt sure about some of the other properties in the string provided by atlas belonged. such as `authSource` , `SSL`, `replicaSet` but now i realize those are mongo client options. and the structured settings servers array gets built into all that as the uri. 

`mongodb://<Username>:<PASSWORD>@cluster0-shard-00-00-ynenp.mongodb.net:27017,cluster0-shard-00-01-ynenp.mongodb.net:27017,cluster0-shard-00-02-ynenp.mongodb.net:27017/<DATABASE>?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin`
