### ISSUE TITLE
[Question] How to create sub-doc with key _id ObjectId automatically?

### ISSUE THREAD

**Issue by dinfer** [SierraSoftworks/Iridium#87]
Thanks for your awesome Iridium. 
I got a question that is there a way to create sub document with generated ObjectId, I use mongoose before, and it's very easy to manage sub-document using it's ObjectId. Is there some equivalent in Iridium?

**Comment by SPARTAN563** [comment]
Hi @dinfer,

I've actually recently answered this for someone else via email, so let me copy the response I sent him here:

Your best bet will be to add a document level transform which checks for `docs` which are missing the `id` field and populates that.

The following is how I'd probably do this, of course, you're more than welcome to do it in a different way and even avoid the generic mutateField method for the sake of brevity, by writing a specific method to perform the action for your document type.

```typescript
import * as Iridium from "iridium";

interface MySubDoc {
    id: number;
}

interface MyDoc {
    id?: string;
    subdocs: MySubDoc[];
}

@Iridium.Collection("mydocs")
@Iridium.Transform(doc => doc, doc => mutateField(doc, "subdocs", subdocs => subdocs.forEach(x => x.id = x.id || generateID())))
class MyInstance extends Iridium.Instance<MyDoc, MyInstance> {
    id: string;
    subdocs: MySubDoc[];
}

/**
 * Helper function for mutating a field of a document in a typesafe manner
 * while returning the document.
 * @param doc The document on which the field exists
 * @param field The field to mutate
 * @param mutate A method which is called to mutate the field 
 */
function mutateField<S, T extends keyof S>(doc: S, field: T, mutate: (field: S[T])=>void): S {
    mutate(doc[field]);
    return doc
}
```

**Comment by dinfer** [comment]
Thank you 👍
