### ISSUE TITLE
Incorrectly implements interface

### ISSUE THREAD

**Issue by Kaffiend** [SierraSoftworks/Iridium#89]
Just started getting these, just updated.
```
Error at node_modules\iridium\dist\lib\cacheControllers\IDDirector.d.ts:8:22: Class 'CacheOnID' incorrectly implements interface 'CacheDirector'.
  Types of property 'valid' are incompatible.
    Type '(object: { [prop: string]: any; _id: any; }) => boolean' is not assignable to type '<T>(object: T) => boolean'.
      Types of parameters 'object' and 'object' are incompatible.
        Type 'T' is not assignable to type '{ [prop: string]: any; _id: any; }'.
Error at node_modules\iridium\dist\lib\caches\NoOpCache.d.ts:11:22: Class 'NoOpCache' incorrectly implements interface 'Cache'.
  Types of property 'get' are incompatible.
    Type '<T>(key: string) => Bluebird<void>' is not assignable to type '<T>(key: string) => PromiseLike<T>'.
      Type 'Bluebird<void>' is not assignable to type 'PromiseLike<T>'.
        Types of property 'then' are incompatible.
          Type '{ <U>(onFulfill?: (value: void) => U | PromiseLike<U>, onReject?: (error: any) => U | PromiseLike...' is not assignable to type '<TResult1 = T, TResult2 = never>(onfulfilled?
: (value: T) => TResult1 | PromiseLike<TResult1>, on...'.
            Types of parameters 'onFulfill' and 'onfulfilled' are incompatible.
              Types of parameters 'value' and 'value' are incompatible.
                Type 'void' is not assignable to type 'T'.
```

**Comment by SPARTAN563** [comment]
Hi Ian, 
I suspect you've just upgraded to TypeScript 2.4 and are still running Iridium 7.x? Unfortunately some of the stricter generic checks in TypeScript 2.4 broke Iridium 7, however I've fixed those on the 8.0.0-alpha.2 version (@next) and am currently doing an opt-in test phase to make sure that there are no issues with it before I release it as the default version. 

Please let me know if that solves it for you. 

Regards, 
Benjamin

**Comment by Kaffiend** [comment]
Library aside this is why i love iridium. Your response time is bar-none. Thank you, that solved it.

**Comment by SPARTAN563** [comment]
I'm glad to hear that fixed the issue, please don't hesitate to let me know if you encounter any issues with the `v8.0.0-alpha`, I'll try to keep it as stable as possible throughout the `alpha` period, but it is less thoroughly proven than `7.x`.

Always a pleasure to help out,
Benjamin

**Comment by Kaffiend** [comment]
You need a “Powered By: Iridium” badge :grin:

Ian Mackie
Lead Developer
Complete System Support, Inc.
O: 304.428.2143
F: 304.428.2145
